### ISSUE TITLE
 feedparser解析失败

### ISSUE THREAD

**Issue by RyougiShiro** [zyujs/rss#4]
地河佬变更了域名rsshub.dihe.moe后， feedparser解析显示下面的内容，不清楚什么原因。。。
{'feed': {}, 'entries': [], 'bozo': 1, 'encoding': 'utf-8', 'version': '', 'bozo_exception': SAXParseException('no element found'), 'namespaces': {}}

**Comment by zyujs** [comment]
这种一般是服务器被源站ban了，建议自行搭建rsshub.

**Comment by RyougiShiro** [comment]
确实是这个原因，自行搭建后就正常了，谢谢
