### ISSUE TITLE
添加rss报错AttributeError

### ISSUE THREAD

**Issue by MiuClips-F** [zyujs/rss#5]
![image](https://user-images.githubusercontent.com/28744408/123232815-185cf080-d50c-11eb-8eb0-624f669e9377.png)
添加就会报错，其他正常，请问大佬可能是什么原因呢

**Comment by zyujs** [comment]
rsshub服务器无法连接

**Comment by MiuClips-F** [comment]
> rsshub服务器无法连接

大佬你好，我用别人的rsshub也不行。而且都能ping通，会不会是依赖版本的问题呢？

**Comment by zyujs** [comment]
和依赖没关系, 换服务器要改data.json里面的rsshub项目, 改rss.py没用. 改完重启hoshino

**Comment by MiuClips-F** [comment]
> 和依赖没关系, 换服务器要改data.json里面的rsshub项目, 改rss.py没用. 改完重启hoshino

![image](https://user-images.githubusercontent.com/28744408/123364518-1f850c80-d5a7-11eb-9fed-08c178b1566f.png)
data.json确实是改过的，而且hoshino也重启过了，但还是一添加就报错

**Comment by zyujs** [comment]
你这图第一个rsshub.app的源需要代理访问, 第二个没开推特支持

**Comment by MiuClips-F** [comment]
> 你这图第一个rsshub.app的源需要代理访问, 第二个没开推特支持

推特支持是开了的，用的别人搭好的。代理访问我的服务器在外面的也需要么，等会我添加代理试一下子，谢谢大佬了
