### ISSUE TITLE
Python3.9报错'HTMLParser' object has no attribute 'unescape'

### ISSUE THREAD

**Issue by SlightDust** [zyujs/rss#6]
咱不太会pr，所以提个issue大佬们改一下吧。
python3.4版本之后html.parser.HTMLParser.unescape()被html.parser.unescape()代替了，python3.9彻底弃用前者。
所以头文件里导入一下html.parser.unescape，然后generate_image(url_list)里把url = HTMLParser.unescape(url)改成url = unescape(url)就好使了。也能保证python3.4到3.9的兼容性。感谢大佬改一改。

**Comment by SlightDust** [comment]
补个图
![image](https://user-images.githubusercontent.com/53001305/130931110-a67001d2-51e4-4887-a140-89132c28ea44.png)
![image](https://user-images.githubusercontent.com/53001305/130931244-08582ab3-39a6-4b52-bdfa-858dfded86eb.png)

**Comment by zyujs** [comment]
好的, 我研究一下
