### ISSUE TITLE
推送问题

### ISSUE THREAD

**Issue by dfmjndm** [zyujs/rss#8]
希望可以限定某条rss只在指定群推送。
现在在任意一个群里rss addr之后所有群里都会推送这个消息。
我尝试在data.json中给某个群添加单独一个rss，但是每次schedule work后会被刷掉。

**Comment by zyujs** [comment]
没有遇到过你说的问题, 请确认你用的不是其他人的魔改版本.

**Comment by dfmjndm** [comment]
换回来了
