### ISSUE TITLE
Hoshino报错

### ISSUE THREAD

**Issue by chenchenriver** [zyujs/rss#9]
![ZA5W7P47(V@X@% %G}HXPOA](https://user-images.githubusercontent.com/93070768/138592037-b879e56a-4f39-4c4c-a0d1-9d00359e542c.png)
Python3.9报错。。请问是我的版本太高了的原因吗

**Comment by zyujs** [comment]
git pull更新一下 ，你的版本太老了

**Comment by chenchenriver** [comment]
已经是rss的最新的了，是需要更新bot或者Python吗

**Comment by zyujs** [comment]
我的代码并未用到decodestring，不明白这个报错是怎么回事。建议换Python3.8

**Comment by chenchenriver** [comment]
好的感谢

**Comment by zyujs** [comment]
看起来像是这个版本python的base64库的bug

**Comment by chenchenriver** [comment]
好的，晚上我研究一下版本问题吧~
